FROM alpine:3

LABEL author="Refaldy Bagas Anggana"
LABEL company="Rebagasa" website="www.refaldybagasanggana.com"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"